server:
  port: 8081

spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
consumer:
  names:
    all-logging:
      queue: all.logging.queue
    partial-logging:
      queue: partial.logging.queue
      exchange: partial.logging.exchange
      routing-key: partial
    image:
      queue: image.queue