spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
producer:
  names:
    all-logging:
      queue: all.logging.queue
    partial-logging:
      queue: partial.logging.queue
      exchange: partial.logging.exchange
      routing-key: partial
    image:
      queue: image.queue
      reply-queue: image.reply.queue
      store-queue: image.store.queue
      exchange: image.exchange

springdoc:
  swagger-ui.path: /api